### ISSUE TITLE
视频合成功能求助

### ISSUE THREAD

**Issue by LucklyLuke** [chenliang15405/ffmpeg-common#1]
作者你好：
    想问一下你这里有没有视频合成的功能，就是准备了好几个视频，合并成一个大的视频。可以按照顺序合成。

**Comment by chenliang15405** [comment]
你好，目前release版本没有此功能，会在下个版本加入此功能，尽快发布
感谢提出功能需求🌹🌹👍

**Comment by chenliang15405** [comment]
release version 3.2 视频合并功能
